apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: add-baremetal-workers
spec:
  params:
    - name: cluster-name
      type: string
    - name: pipeline-image
      type: string
  steps:
    - name: add-workers
      image: $(params.pipeline-image)
      imagePullPolicy: IfNotPresent
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        fleet-add-baremetal-workers \
          --cluster-name "$(params.cluster-name)" \
          --pipeline-image "$(params.pipeline-image)"
