apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-pipeline-config
data:
  keycloak-url: "https://keycloak.example.com"
  keycloak-realm: "openshift"
  keycloak-admin-secret: "keycloak-admin"
  keycloak-issuer-url: "https://keycloak.example.com/realms/openshift"
  base-domain: "example.com"
  acme-email: "admin@example.com"
  auth-realm: "master"
  provider-name: "RedHat"
  insecure: "false"
  git-repo-url: "https://github.com/yashoza19/fleet.git"
  git-revision: "ocpv-post-provision"
  pipeline-image: "quay.io/yoza/fleet-pipeline:0.0.2"
  openshift-cluster: "true"
  cluster-admins: ""
  clusters-repo: "redhat-openshift-partner-labs/fleet-clusters"
  clusters-repo-revision: "main"
  github-app-id: ""
  github-app-installation-id: ""
  github-app-key-secret: "fleet-github-app-key"
