apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemesh-namespace.yaml
  - servicemesh-subscription.yaml
  - serverless-namespace.yaml
  - serverless-operatorgroup.yaml
  - serverless-subscription.yaml
  - authorino-subscription.yaml
