apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - eventlistener.yaml
  - triggerbinding-pre-provision.yaml
  - triggertemplate-pre-provision.yaml
  - triggerbinding-deprovision.yaml
  - triggertemplate-deprovision.yaml
  - triggerbinding-post-provision.yaml
  - triggertemplate-post-provision.yaml
