---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: post-provision-binding
spec:
  params:
    - name: cluster-name
      value: $(body.cluster_name)
    - name: tier
      value: $(body.tier)
    - name: dns-zones
      value: $(body.dns_zones)
    - name: base-domain
      value: $(body.base_domain)
    - name: keycloak-issuer-url
      value: $(body.keycloak_issuer_url)
    - name: keycloak-url
      value: $(body.keycloak_url)
    - name: keycloak-realm
      value: $(body.keycloak_realm)
    - name: keycloak-admin-secret
      value: $(body.keycloak_admin_secret)
    - name: auth-realm
      value: $(body.auth_realm)
    - name: acme-email
      value: $(body.acme_email)
