apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-phase-2-gpu
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-openshift-partner-labs/fleet.git
    targetRevision: main
    path: workloads/ai/phase-2-gpu
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
