apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfd-subscription.yaml
  - nfd-operand.yaml
  - gpu-operator-subscription.yaml
  - openshift-ai-subscription.yaml
  - serverless-subscription.yaml
  - datasciencecluster.yaml
