apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfd-subscription.yaml
  - nfd-operand.yaml
  - nvidia-gpu-subscription.yaml
  - nvidia-gpu-cluster-policy.yaml
  - serverless-subscription.yaml
  - authorino-subscription.yaml
